#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../modules.sh"

require-module testing
require-module file

### Test fixture

temp-file -d -v fixtureDir
temp-file -v testFile

# a1: inexistent file
a1parent0="$fixtureDir"
a1parent1="$(dirname "$a1parent0")"
a1parent2="$(dirname "$a1parent1")"
a1rel0="a1"
a1rel1="$(basename "$a1parent0")/$a1rel0"
a1rel2="$(basename "$a1parent1")/$a1rel1"
a1abs="$a1parent0/a1"

### Test suites.

test-suite "File naming"

absolute-dirname "." | outputs "$PWD"
absolute-dirname "./" | outputs "$PWD"

absolute-path "." | outputs "$PWD"
absolute-path "./" | outputs "$PWD"

relative-filename -b "$a1parent0" "$a1abs" | outputs "$a1rel0"
relative-filename -b "$a1parent1" "$a1abs" | outputs "$a1rel1"
relative-filename -b "$a1parent2" "$a1abs" | outputs "$a1rel2"

pushd "$a1parent0" > /dev/null
absolute-filename "$a1rel0" | outputs "$a1abs"
cd .. && absolute-filename "$a1rel1" | outputs "$a1abs"
cd .. && absolute-filename "$a1rel2" | outputs "$a1abs"
popd > /dev/null

test-suite "File attributes"

echo -n "abc" > "$testFile"
file-size "$testFile" | outputs 3
